local boxes          = {}
local box_group      = -1
local ray_start      = vmath.vector3(0, 0, 0)
local ray_end        = vmath.vector3(365, 370, 0)
local query_result   = {}
local result_count   = 0
local collision_bits = {
    PLAYER = 1,          -- (2^0)
    ENEMY  = 2,          -- (2^1)
    ITEM   = 4,          -- (2^2)
    ALL    = bit.bnot(0) -- -1 for all results
}
local mask_bits      = bit.bor(collision_bits.ENEMY, collision_bits.ITEM)


function init(self)
    msg.post(".", "acquire_input_focus")
    msg.post("@render:", "use_camera_projection")



    if profiler then
        profiler.enable_ui(true)
        profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)
    end
end

function update(self, dt)
end

function on_input(self, action_id, action)

end
